name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: KUNKing777
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=green&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39&

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
